version: "3.8"

volumes:
  service_postgres_data:
  pip_cache:


services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - service_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env-vars/.postgres.env

  service:
    container_name: service
    build:
      context: .
    command: [ "./start_service.sh" ]
    ports:
      - "8080:80" # Main port
      - "8181:8181" # Debug port
    volumes:
      - ./src:/src
      - pip_cache:/usr/local/lib/python3/site-packages
    env_file:
      - ./env-vars/.service.env
      - ./env-vars/.postgres.env
    depends_on:
      - db
