name: Deploy Service

on:
    push:
        branches:
            - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -tt -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          cd msg-service &&

          echo "Fetching changes from repository..." &&

          sudo git pull &&

          echo "Building images..." &&

          sudo docker-compose build &&

          echo "Running docker-compose up..." &&

          sudo docker-compose up -d &&

          echo "Deployment complete."       
        '
