name: Deploy Service

on:
  push:
    branches: [ develop ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_EC2_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              cd msg-service &&

              echo "Fetching changes from repository..." &&

              sudo git pull &&

              echo "Building images..." &&

              sudo docker-compose build &&

              echo "Running docker-compose up..." &&

              sudo docker-compose up -d &&

              echo "Deployment complete."
              '
