name: Rodar Testes

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar requirements
        run: pip install -r requirements.txt

      - name: Instalar tox
        run: pip install tox

      - name: Rodar testes
        run: tox

      - name: Rodar Migrations
        run: |
          python src/manage.py migrate
          python src/manage.py makemigrations --check --dry-run

      - name: Corrige reports path
        run: |
          sed -i 's/<source>\/home\/runner\/work\/2023-2-MeasureSoftGram-Service\/2023-2-MeasureSoftGram-Service<\/source>/<source>\/github\/workspace<\/source>/g' coverage.xml
          sed -i 's/classname="/classname="src./g' junit.xml

      - name: Scanner do SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Envia cobertura para o Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: 2023-1-MeasureSoftGram-Service
          verbose: true
